gatling.enterprise.package {
  name = "Ecomm-App-JS"
  team = "SRE/DevOps"
  default {
    simulation {
      locations = [
        {
          name: "Europe - Paris",
          size: 1,
          weight: 70
        },
        {
          name: "Europe - Dublin",
          size: 1,
          weight: 30
        }
      ]
      stopCriteria = [
        {
          type = "meanCpu",
          timeFrameInSeconds = 15,
          threshold = {
            maxPercentage = 85
          }
        }
      ]
      parameters {
        ignoreDefaults = true
        systemProperties {
          "env": "DEV"
          "minPauseSec": "5"
          "maxPauseSec": "15"
        }
        environmentVariables {}
      }
    }
  }
  simulations = [
    {
      name = "Stress-Test-JS"
      simulation = "advanced"
      parameters {
        systemProperties {
          "testType": "stress"
          "durationMinutes": "5"
          "vu": "10000"
        }
      }
    }
  ]
}
