version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "maven"
    directory: "/java/maven"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gradle"
    directory: "/java/gradle"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gradle"
    directory: "/kotlin"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "maven"
    directory: "/scala/maven"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gradle"
    directory: "/scala/gradle"
    schedule:
      interval: "weekly"
      day: "sunday"
