version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
      day: "sunday"
