version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
  - package-ecosystem: "sbt"
    directory: "/scala"
    schedule:
      interval: "weekly"
