version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "maven"
    directory: "/java"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/javascript"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    directory: "/typescript"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gradle"
    directory: "/kotlin/gradle"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "maven"
    directory: "/kotlin/maven"
    schedule:
      interval: "weekly"
      day: "sunday"
