version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "gradle"
    commit-message:
      prefix: "chore"
    directories:
      - "/java/gradle"
      - "/kotlin/gradle"
      - "/scala/gradle"
    groups:
      gatling:
        patterns:
          - "io.gatling*"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "maven"
    commit-message:
      prefix: "chore"
    directories:
      - "/java/maven"
      - "/kotlin/maven"
      - "/scala/maven"
    groups:
      gatling:
        patterns:
          - "io.gatling*"
    schedule:
      interval: "weekly"
      day: "sunday"
  - package-ecosystem: "npm"
    commit-message:
      prefix: "chore"
    directories:
      - "/javascript"
      - "/typescript"
      - "/postman/javascript"
      - "/postman/typescript"
    groups:
      gatling:
        patterns:
          - "@gatling.io/*"
    schedule:
      interval: "weekly"
      day: "sunday"
