gatling.enterprise.package {
  name = "Ecomm-App-Java"
  team = "SRE/DevOps"
  default {
    simulation {
      locations = [
        {
          name: "Europe - Paris",
          size: 1,
          weight: 70
        },
        {
          name: "Europe - Dublin",
          size: 1,
          weight: 30
        }
      ]
      stopCriteria = [
        {
          type = "meanCpu",
          timeFrameInSeconds = 15,
          threshold = {
            maxPercentage = 85
          }
        }
      ]
      parameters {
        ignoreDefaults = true
        systemProperties {
          "env": "DEV"
          "minPauseSec": "5"
          "maxPauseSec": "15"
        }
        environmentVariables {}
      }
    }
  }
  simulations = [
    {
      name = "Stress-Test"
      simulation = "example.AdvancedSimulation"
      parameters {
        systemProperties {
          "testType": "stress"
          "durationMinutes": "5"
          "vu": "10000"
        }
      }
    },
    {
      name = "Capacity-Test"
      simulation = "example.AdvancedSimulation"
      parameters {
        systemProperties {
          "testType": "capacity"
          "durationMinutes": "1"
          "vu": "100"
        }
      }
    },
    {
      name = "Soak-Test"
      simulation = "example.AdvancedSimulation"
      parameters {
        systemProperties {
          "testType": "soak"
          "durationMinutes": "30"
          "vu": "1000"
        }
      }
    },
    {
      name = "Breakpoint-Test"
      simulation = "example.AdvancedSimulation"
      parameters {
        systemProperties {
          "testType": "breakpoint"
          "durationMinutes": "5"
          "vu": "1000"
        }
      }
    }
  ]
}
